function [soilStates, thetaStates] = initializeSoilStates(params, nNode)
% INITIALIZESOILSTATES Initialize soil state variables for p-y and m-theta curves
%
% Inputs:
%   params - Structure containing simulation parameters
%   nNode  - Number of nodes
%
% Outputs:
%   soilStates  - Array of structures for p-y curve state
%   thetaStates - Array of structures for m-theta curve state

% Initialize empty state structure for p-y curves
emptyState = struct( ...
    'y_prev', 0, ...
    'p_prev', 0, ...
    'direction', 0, ...
    'y_rev', 0, ...
    'p_rev', 0, ...
    'k_unload', 0 ...
);

% Initialize empty state structure for m-theta curves
emptyThetaState = struct( ...
    'theta_prev', 0, ...
    'm_prev', 0, ...
    'direction', 0 ...
);

% Create arrays of state structures
soilStates = repmat(emptyState, nNode, 1);
thetaStates = repmat(emptyThetaState, nNode, 1);

end