site_name: MonoSim
site_description: Monopile Simulator for Offshore Wind Turbines
repo_url: https://github.com/yourusername/MonoSim

nav:
  - Home: index.md
  - User Guide: docs/user-guide.md
  - Technical Documentation:
    - Finite Element Method: docs/finite-element-method.md
    - Time Integration: docs/time-integration.md
    - Aerodynamics: docs/aerodynamics.md
    - Hydrodynamics: docs/hydrodynamics.md
    - Soil Dynamics: docs/soil-dynamics.md
  - Contributing: CONTRIBUTING.md

theme: readthedocs